# Generated by Django 4.2.23 on 2025-09-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrcentre', '0002_userscheck_negate_userscheck_operator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CharacterAuditLoginData',
        ),
    ]
