# coding: utf-8

"""
    Agent Hosting API

      ## Overview  The Agent Hosting API helps users deploy agents to the cloud  ## Authentication  The entire API requires that the user authenticate with the ecosystem first before accessing the api 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.hosting.models.agent_geolocation import AgentGeolocation

class TestAgentGeolocation(unittest.TestCase):
    """AgentGeolocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentGeolocation:
        """Test AgentGeolocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentGeolocation`
        """
        model = AgentGeolocation()
        if include_optional:
            return AgentGeolocation(
                latitude = -90.0,
                longitude = -180.0,
                radius = 1.337
            )
        else:
            return AgentGeolocation(
                latitude = -90.0,
                longitude = -180.0,
        )
        """

    def testAgentGeolocation(self):
        """Test AgentGeolocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
