from weakref import ref
import random
from qtmui.lib.qtcompat.QtGui import QPen, QPainter, QColor, QPixmap, QIcon
from qtmui.lib.qtcompat.QtCore import Qt, QVariantAnimation, QRectF, QEasingCurve, QSize
from qtmui.lib.qtcompat.QtWidgets import QApplication, QPushButton
from qtmui.material.styles import useTheme
class Arc:
    def __init__(self): ...
class LoadingIcon:
    def __init__(self, button: QPushButton, diameter, parent): ...
    def startAnime(self): ...
    def updatePixmap(self, value): ...
    def stopAnimation(self): ...