"""
RFS Advanced Analytics (RFS v4.1)

고급 분석 및 대시보드 시스템
"""

from .charts import (  # 차트 시스템; 차트 구현체; 차트 빌더
    BarChart,
    Chart,
    ChartBuilder,
    ChartData,
    ChartOptions,
    ChartType,
    HeatmapChart,
    HistogramChart,
    LineChart,
    PieChart,
    ScatterChart,
    create_chart,
)
from .dashboard import (  # 대시보드 시스템; 위젯 구현체; 대시보드 빌더; 대시보드 관리
    ChartWidget,
    Dashboard,
    DashboardBuilder,
    DashboardLayout,
    DashboardManager,
    MetricWidget,
    TableWidget,
    TextWidget,
    Widget,
    WidgetType,
    create_dashboard,
    get_dashboard_manager,
)
from .data_source import (  # 데이터 소스; 데이터 소스 구현체; 데이터 소스 관리
    APIDataSource,
    DatabaseDataSource,
    DataQuery,
    DataSource,
    DataSourceManager,
    DataSourceType,
    FileDataSource,
    MetricsDataSource,
    register_data_source,
)
from .kpi import (  # KPI 관리; KPI 타입; KPI 대시보드
    KPI,
    AverageKPI,
    CountKPI,
    KPICalculator,
    KPIDashboard,
    KPIThreshold,
    PercentageKPI,
    TrendKPI,
    create_kpi_dashboard,
)
from .reports import (  # 리포트 시스템; 리포트 타입; 리포트 생성; 리포트 템플릿
    ExcelReport,
    HTMLReport,
    PDFReport,
    Report,
    ReportBuilder,
    ReportSection,
    ReportTemplate,
    create_report_template,
    generate_report,
    schedule_report,
)
from .visualization import (  # 시각화 엔진; 시각화 유틸리티; 테마 관리
    ColorScheme,
    DarkTheme,
    DefaultTheme,
    PlotConfig,
    Theme,
    VisualizationEngine,
    apply_theme,
    create_interactive_plot,
    export_chart,
    generate_plot,
)

__all__ = [
    # Dashboard
    "Dashboard",
    "DashboardLayout",
    "Widget",
    "WidgetType",
    "ChartWidget",
    "MetricWidget",
    "TableWidget",
    "TextWidget",
    "DashboardBuilder",
    "create_dashboard",
    "DashboardManager",
    "get_dashboard_manager",
    # Charts
    "Chart",
    "ChartType",
    "ChartData",
    "ChartOptions",
    "LineChart",
    "BarChart",
    "PieChart",
    "ScatterChart",
    "HistogramChart",
    "HeatmapChart",
    "ChartBuilder",
    "create_chart",
    # Data Source
    "DataSource",
    "DataSourceType",
    "DataQuery",
    "DatabaseDataSource",
    "FileDataSource",
    "APIDataSource",
    "MetricsDataSource",
    "DataSourceManager",
    "register_data_source",
    # Visualization
    "VisualizationEngine",
    "PlotConfig",
    "ColorScheme",
    "generate_plot",
    "export_chart",
    "create_interactive_plot",
    "Theme",
    "DefaultTheme",
    "DarkTheme",
    "apply_theme",
    # Reports
    "Report",
    "ReportBuilder",
    "ReportSection",
    "PDFReport",
    "HTMLReport",
    "ExcelReport",
    "generate_report",
    "schedule_report",
    "ReportTemplate",
    "create_report_template",
    # KPI
    "KPI",
    "KPICalculator",
    "KPIThreshold",
    "CountKPI",
    "AverageKPI",
    "PercentageKPI",
    "TrendKPI",
    "KPIDashboard",
    "create_kpi_dashboard",
]
