! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


SUBROUTINE C_CALC_FPK_PBC(XPOS_DIM_1, XPOS, YPOS_DIM_1, YPOS, BX_DIM_1, BX, BY_DIM_1, BY, TAU0, LEN_X, LEN_Y, FPK_DIM_1, FPK_DIM_2,&
& FPK, NMOB, N) BIND(C)
  USE ISO_C_BINDING, ONLY: C_BOOL
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: XPOS_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(XPOS_DIM_1) :: XPOS
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: YPOS_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(YPOS_DIM_1) :: YPOS
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: BX_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(BX_DIM_1) :: BX
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: BY_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(BY_DIM_1) :: BY
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: TAU0
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: LEN_X
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: LEN_Y
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FPK_DIM_1
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FPK_DIM_2
  REAL(KIND=KIND ( 0.0D0 )), INTENT(OUT), DIMENSION(FPK_DIM_1,FPK_DIM_2) :: FPK
  INTEGER, INTENT(IN) :: NMOB
  INTEGER, INTENT(IN) :: N

  INTERFACE
    SUBROUTINE CALC_FPK_PBC(XPOS, YPOS, BX, BY, TAU0, LEN_X, LEN_Y, FPK, NMOB, N)
      ! Solution based on Eqs (2.1.25a) and (2.1.25b) from Linyong Pang "A new O(N) method for
      ! modeling and simulating the behavior of a large number of dislocations in
      ! anisotropic linear elastic media", PhD thesis, Stanford University, USA. 2001
      IMPLICIT NONE
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: XPOS
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: YPOS
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: BX
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: BY
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: TAU0
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: LEN_X
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: LEN_Y
      REAL(KIND=KIND ( 0.0D0 )), INTENT(OUT), DIMENSION(2,NMOB) :: FPK
      INTEGER, INTENT(IN) :: NMOB
      INTEGER, INTENT(IN) :: N
    END SUBROUTINE CALC_FPK_PBC
  END INTERFACE

  CALL CALC_FPK_PBC(XPOS, YPOS, BX, BY, TAU0, LEN_X, LEN_Y, FPK, NMOB, N)
END SUBROUTINE C_CALC_FPK_PBC


SUBROUTINE C_CALC_FPK(XPOS_DIM_1, XPOS, YPOS_DIM_1, YPOS, BX_DIM_1, BX, BY_DIM_1, BY, TAU0, FPK_DIM_1, FPK_DIM_2, FPK, NMOB, N) BIN&
&D(C)
  USE ISO_C_BINDING, ONLY: C_BOOL
  IMPLICIT NONE
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: XPOS_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(XPOS_DIM_1) :: XPOS
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: YPOS_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(YPOS_DIM_1) :: YPOS
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: BX_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(BX_DIM_1) :: BX
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: BY_DIM_1
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(BY_DIM_1) :: BY
  REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: TAU0
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FPK_DIM_1
  INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: FPK_DIM_2
  REAL(KIND=KIND ( 0.0D0 )), INTENT(OUT), DIMENSION(FPK_DIM_1,FPK_DIM_2) :: FPK
  INTEGER, INTENT(IN) :: NMOB
  INTEGER, INTENT(IN) :: N

  INTERFACE
    SUBROUTINE CALC_FPK(XPOS, YPOS, BX, BY, TAU0, FPK, NMOB, N)
      IMPLICIT NONE
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: XPOS
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: YPOS
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: BX
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN), DIMENSION(N) :: BY
      REAL(KIND=KIND ( 0.0D0 )), INTENT(IN) :: TAU0
      REAL(KIND=KIND ( 0.0D0 )), INTENT(OUT), DIMENSION(2,NMOB) :: FPK
      INTEGER, INTENT(IN) :: NMOB
      INTEGER, INTENT(IN) :: N
    END SUBROUTINE CALC_FPK
  END INTERFACE

  CALL CALC_FPK(XPOS, YPOS, BX, BY, TAU0, FPK, NMOB, N)
END SUBROUTINE C_CALC_FPK

