# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AssistantResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'thread_id': 'str',
        'messages': 'list[AssistantMessage]',
        'next_actions': 'list[AssistantRequest]'
    }

    attribute_map = {
        'thread_id': 'threadId',
        'messages': 'messages',
        'next_actions': 'nextActions'
    }

    def __init__(self, thread_id=None, messages=None, next_actions=None):  # noqa: E501
        """AssistantResponse - a model defined in Swagger"""  # noqa: E501
        self._thread_id = None
        self._messages = None
        self._next_actions = None
        self.discriminator = None
        if thread_id is not None:
            self.thread_id = thread_id
        if messages is not None:
            self.messages = messages
        if next_actions is not None:
            self.next_actions = next_actions

    @property
    def thread_id(self):
        """Gets the thread_id of this AssistantResponse.  # noqa: E501


        :return: The thread_id of this AssistantResponse.  # noqa: E501
        :rtype: str
        """
        return self._thread_id

    @thread_id.setter
    def thread_id(self, thread_id):
        """Sets the thread_id of this AssistantResponse.


        :param thread_id: The thread_id of this AssistantResponse.  # noqa: E501
        :type: str
        """

        self._thread_id = thread_id

    @property
    def messages(self):
        """Gets the messages of this AssistantResponse.  # noqa: E501


        :return: The messages of this AssistantResponse.  # noqa: E501
        :rtype: list[AssistantMessage]
        """
        return self._messages

    @messages.setter
    def messages(self, messages):
        """Sets the messages of this AssistantResponse.


        :param messages: The messages of this AssistantResponse.  # noqa: E501
        :type: list[AssistantMessage]
        """

        self._messages = messages

    @property
    def next_actions(self):
        """Gets the next_actions of this AssistantResponse.  # noqa: E501


        :return: The next_actions of this AssistantResponse.  # noqa: E501
        :rtype: list[AssistantRequest]
        """
        return self._next_actions

    @next_actions.setter
    def next_actions(self, next_actions):
        """Sets the next_actions of this AssistantResponse.


        :param next_actions: The next_actions of this AssistantResponse.  # noqa: E501
        :type: list[AssistantRequest]
        """

        self._next_actions = next_actions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AssistantResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AssistantResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
