# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ResourceSyncRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_name': 'str',
        'environment_name': 'str',
        'resources': 'list[FacetsResource]'
    }

    attribute_map = {
        'project_name': 'projectName',
        'environment_name': 'environmentName',
        'resources': 'resources'
    }

    def __init__(self, project_name=None, environment_name=None, resources=None):  # noqa: E501
        """ResourceSyncRequest - a model defined in Swagger"""  # noqa: E501
        self._project_name = None
        self._environment_name = None
        self._resources = None
        self.discriminator = None
        if project_name is not None:
            self.project_name = project_name
        if environment_name is not None:
            self.environment_name = environment_name
        if resources is not None:
            self.resources = resources

    @property
    def project_name(self):
        """Gets the project_name of this ResourceSyncRequest.  # noqa: E501


        :return: The project_name of this ResourceSyncRequest.  # noqa: E501
        :rtype: str
        """
        return self._project_name

    @project_name.setter
    def project_name(self, project_name):
        """Sets the project_name of this ResourceSyncRequest.


        :param project_name: The project_name of this ResourceSyncRequest.  # noqa: E501
        :type: str
        """

        self._project_name = project_name

    @property
    def environment_name(self):
        """Gets the environment_name of this ResourceSyncRequest.  # noqa: E501


        :return: The environment_name of this ResourceSyncRequest.  # noqa: E501
        :rtype: str
        """
        return self._environment_name

    @environment_name.setter
    def environment_name(self, environment_name):
        """Sets the environment_name of this ResourceSyncRequest.


        :param environment_name: The environment_name of this ResourceSyncRequest.  # noqa: E501
        :type: str
        """

        self._environment_name = environment_name

    @property
    def resources(self):
        """Gets the resources of this ResourceSyncRequest.  # noqa: E501


        :return: The resources of this ResourceSyncRequest.  # noqa: E501
        :rtype: list[FacetsResource]
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this ResourceSyncRequest.


        :param resources: The resources of this ResourceSyncRequest.  # noqa: E501
        :type: list[FacetsResource]
        """

        self._resources = resources

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ResourceSyncRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResourceSyncRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
