from ..entity.upload import UploadFileModel as UploadFileModel
from fastapi import UploadFile as UploadFile

class UploadService:
    def __init__(self, path_name: str, disk_name: str = 'Upload') -> None: ...
    def get_file_path(self, file_name: str): ...
    def list_files(self): ...
    async def save_files(self, files: list[UploadFile] = ...): ...
    async def delete_files(self, files: list[UploadFileModel]): ...
