# Generated by Django 5.1.8 on 2025-08-06 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_certificate_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='predecessor_certificate',
        ),
        migrations.AddField(
            model_name='certificate',
            name='authority_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='successor_certificates',
        ),
        migrations.AddField(
            model_name='certificate',
            name='successor_certificates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='successor_certificate', to='adestis_netbox_certificate_management.certificate'),
        ),
    ]
