# Generated by Django 5.1.8 on 2025-08-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_certificate_management', '0002_remove_certificate_predecessor_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='custom_field_data',
        ),
        migrations.AddField(
            model_name='certificate',
            name='format',
            field=models.CharField(default='pfx', max_length=50),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pfx_password',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='authority_identifier',
            field=models.CharField(blank=True, max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key_technology',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subject',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subject_alternative_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subject_key_identifier',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='supplier_product',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
