# Generated by Django 5.2.5 on 2025-09-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adestis_netbox_certificate_management', '0005_remove_certificate_successor_certificates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='successor_certificates',
        ),
    ]
