# -*- coding: utf-8 -*-

"""
cypresstestapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status1Enum(object):

    """Implementation of the 'status1' enum.

    Attributes:
        ENUMVALUE1: The enum member of type str.
        ENUMVALUE2: The enum member of type str.
        ENUMVALUE3: The enum member of type str.

    """
    ENUMVALUE1 = 'enumvalue1'

    ENUMVALUE2 = 'enumvalue2'

    ENUMVALUE3 = 'enumvalue3'

