from ..engine.database_engine import DatabaseEngine as DatabaseEngine
from _typeshed import Incomplete
from collections.abc import Generator

class DBEngineService:
    @classmethod
    def get_async_engine(cls, database_config_name): ...
    @classmethod
    def get_engine(cls, database_config_name): ...
    @classmethod
    async def get_core_session(cls) -> Generator[Incomplete]: ...
    @classmethod
    async def get_common_session(cls) -> Generator[Incomplete]: ...
    @classmethod
    async def get_generate_session(cls) -> Generator[Incomplete]: ...
