class NoteApiUrl:
    NOTE = "/api/v3/notes/{uuid}"

    ACCOUNTS_NOTE = "/api/v3/accounts/{id}/notes"
    ACCOUNTS_NOTE_UUID = "/api/v3/accounts/{id}/notes/{uuid}"
    ACCOUNTS_NOTE_UUID_FILES = "/api/v3/accounts/{id}/notes/{uuid}/files"
    ACCOUNTS_NOTE_UUID_FILES_UUID = "/api/v3/accounts/{id}/notes/{uuid}/files/{file_uuid}"

    ORDER_NOTE = "/api/v3/orders/{id}/notes"
    ORDER_NOTE_UUID = "/api/v3/orders/{id}/notes/{uuid}"
    ORDER_NOTE_UUID_FILES = "/api/v3/orders/{id}/notes/{uuid}/files"
    ORDER_NOTE_UUID_FILES_UUID = "/api/v3/orders/{id}/notes/{uuid}/files/{file_uuid}"
    ORDER_NOTE_ADD = "/api/v2/orders/{id}/notes"
    ORDER_NOTE_UUID_ADD = "/api/v2/orders/{id}/notes/{uuid}"

    ITEM_NOTE = "/api/v3/items/{id}/notes"
    ITEM_NOTE_UUID = "/api/v3/items/{id}/notes/{uuid}"
    ITEM_NOTE_UUID_FILES = "/api/v3/items/{id}/notes/{uuid}/files"
    ITEM_NOTE_UUID_FILES_UUID = "/api/v3/items/{id}/notes/{uuid}/files/{file_uuid}"
    ITEM_NOTE_ADD = "/api/v2/items/{id}/notes"
    ITEM_NOTE_UUID_ADD = "/api/v2/items/{id}/notes/{uuid}"

    INVOICE_NOTE = "/api/v2/invoices/{id}/notes"
    INVOICE_NOTE_UUID = "/api/v2/invoices/{id}/notes/{uuid}"
    INVOICE_NOTE_UUID_FILES = "/api/v2/invoices/{id}/notes/{uuid}/files"
    INVOICE_NOTE_UUID_FILES_UUID = "/api/v2/invoices/{id}/notes/{uuid}/files/{file_uuid}"
    INVOICE_NOTE_ADD = "/api/v2/invoices/{id}/notes"
    INVOICE_NOTE_UUID_ADD = "/api/v2/invoices/{id}/notes/{uuid}"

    PAYMENT_NOTE = "/api/v3/payments/{id}/notes"
    PAYMENT_NOTE_UUID = "/api/v3/payments/{id}/notes/{uuid}"
    PAYMENT_NOTE_UUID_FILES = "/api/v3/payments/{id}/notes/{uuid}/files"
    PAYMENT_NOTE_UUID_FILES_UUID = "/api/v3/payments/{id}/notes/{uuid}/files/{file_uuid}"
    PAYMENT_NOTE_ADD = "/api/v2/payments/{id}/notes"
    PAYMENT_NOTE_UUID_ADD = "/api/v2/payments/{id}/notes/{uuid}"

    PURCHASE_ORDER_NOTE = "/api/v3/purchase-orders/{id}/notes"
    PURCHASE_ORDER_NOTE_UUID = "/api/v3/purchase-orders/{id}/notes/{uuid}"
    PURCHASE_ORDER_NOTE_UUID_FILES = "/api/v3/purchase-orders/{id}/notes/{uuid}/files"
    PURCHASE_ORDER_NOTE_UUID_FILES_UUID = "/api/v3/purchase-orders/{id}/notes/{uuid}/files/{file_uuid}"
    PURCHASE_ORDER_NOTE_ADD = "/api/v2/purchase-orders/{id}/notes"
    PURCHASE_ORDER_NOTE_UUID_ADD = "/api/v2/purchase-orders/{id}/notes/{uuid}"

    PURCHASE_INVOICE_NOTE = "/api/v3/purchase-invoices/{id}/notes"
    PURCHASE_INVOICE_NOTE_UUID = "/api/v3/purchase-invoices/{id}/notes/{uuid}"
    PURCHASE_INVOICE_NOTE_UUID_FILES = "/api/v3/purchase-invoices/{id}/notes/{uuid}/files"
    PURCHASE_INVOICE_NOTE_UUID_FILES_UUID = "/api/v3/purchase-invoices/{id}/notes/{uuid}/files/{file_uuid}"
    PURCHASE_INVOICE_NOTE_ADD = "/api/v2/purchase-invoices/{id}/notes"
    PURCHASE_INVOICE_NOTE_UUID_ADD = "/api/v2/purchase-invoices/{id}/notes/{uuid}"
