def ascents(image: tuple[int, ...]) -> list[int]: ...
def descents(image: tuple[int, ...]) -> list[int]: ...
def exceedances(image: tuple[int, ...], weakly: bool) -> list[int]: ...
def int_repr(image: tuple[int, ...]) -> int: ...
def is_derangement(image: tuple[int, ...]) -> bool: ...
def lehmer_code(image: tuple[int, ...]) -> bool: ...
def lexicographic_rank(image: tuple[int, ...]) -> int: ...
def repr(image: tuple[int, ...]) -> str: ...
