from typing import List, Optional, Tuple

class QuadTree:
    def __init__(self, bounds: Tuple[float, float, float, float], capacity: int = ..., max_depth: Optional[int] = ...) -> None: ...
    def insert(self, id: int, xy: Tuple[float, float]) -> bool: ...
    def query(self, rect: Tuple[float, float, float, float]) -> List[Tuple[int, float, float]]: ...
    def nearest_neighbor(self, xy: Tuple[float, float]) -> Optional[Tuple[int, float, float]]: ...
    def nearest_neighbors(self, xy: Tuple[float, float], k: int) -> List[Tuple[int, float, float]]: ...
