key = """-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIAUeDeLJz7Ast36veGFEaSoUTiQKLFuHZ4JqgT2CHh7poAoGCCqGSM49
AwEHoUQDQgAEOaAq4rxVKFcwKhvnBnkCcj57MMttX9dh79qMgYth50tkp3aNXSZc
NPQHUur09OejfBy3/V9eoXBMj2f3HhoT/Q==
-----END EC PRIVATE KEY-----
"""

cert = """-----BEGIN CERTIFICATE-----
MIIB6TCCAY8CFEq/uOD3yklb0FR3ITccL0U0XJjPMAoGCCqGSM49BAMCMHcxCzAJ
BgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0eTEVMBMGA1UE
CgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25hbCBVbml0MRQw
EgYDVQQDDAtDb21tb24gTmFtZTAeFw0yNTA5MTMxMDM4MjVaFw0zNTA5MTExMDM4
MjVaMHcxCzAJBgNVBAYTAlRXMQ4wDAYDVQQIDAVTdGF0ZTENMAsGA1UEBwwEQ2l0
eTEVMBMGA1UECgwMT3JnYW5pemF0aW9uMRwwGgYDVQQLDBNPcmdhbml6YXRpb25h
bCBVbml0MRQwEgYDVQQDDAtDb21tb24gTmFtZTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABDmgKuK8VShXMCob5wZ5AnI+ezDLbV/XYe/ajIGLYedLZKd2jV0mXDT0
B1Lq9PTno3wct/1fXqFwTI9n9x4aE/0wCgYIKoZIzj0EAwIDSAAwRQIhAIe+zYvB
ylTH27vXomiPRtCMzw42FifKnHtEyKDA6wXyAiBLiB283NBQsJmNACVhz/yKllMB
wjXzSUhrTUBPbsqYyA==
-----END CERTIFICATE-----
"""