import asyncio
import uuid
from typing import Optional, Callable, Union, List, Dict
from qtpy.QtWidgets import QWidget, QVBoxLayout, QFrame, QSizePolicy, QHBoxLayout
from qtpy.QtCore import Signal, QTimer
from qtmui.material.styles import useTheme
from qtmui.material.styles.create_theme.components.get_qss_styles import get_qss_style
from ..widget_base import PyWidgetBase
class Paper:
    def __init__(self, children: Optional[Union[QWidget, List[QWidget]]], classes: Optional[Dict[str, str]], component: Optional[QWidget], direction: str, elevation: int, key: str, square: bool, sx: Optional[Union[List[Union[Callable, dict, bool]], Callable, dict, bool]], variant: str, fullWidth: bool, spacing, onClick: Optional[Callable], width: int, height: int, borderRadius: int, *args, **kwargs): ...
    def _update_stylesheet(self): ...
    def _set_stylesheet(self, component_styled): ...
    def paintEvent(self, arg__1): ...
    def resizeEvent(self, event): ...