# Evolis SDK for Python
#
# THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
# ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.

from enum import Enum

class State:
    """
    List device's possible states.
    """

    class Major(Enum):
        OFF = 0
        READY = 1
        WARNING = 2
        ERROR = 3

    class Minor(Enum):
        PRINTER_UNKNOWN = 0
        PRINTER_OFFLINE = 1
        PRINTER_SUPERVISION_UNINITIALIZED = 2
        PRINTER_SUPERVISION_INITIALIZING = 3
        PRINTER_STATUS_DISABLED = 4
        PRINTER_NOT_SUPERVISED = 5
        PRINTER_READY = 6
        NOT_FLIP_ACT = 7
        BUSY = 8
        INTERNALERROR = 9
        INF_LAMI_CLEANING_RUNNING = 10
        INF_LAMI_TEMP_NOT_READY = 11
        INF_LAMI_UPDATING_FIRMWARE = 12
        INF_LAMINATE_LOW = 13
        INF_LAMINATE_UNKNOWN = 14
        INF_LAMINATING_RUNNING = 15
        DEF_LAMI_COVER_OPEN = 16
        DEF_LAMI_HOPPER_FULL = 17
        DEF_LAMINATE_END = 18
        DEF_LAMINATE_UNSUPPORTED = 19
        DEF_NO_LAMINATE = 20
        ERR_LAMI_COVER_OPEN = 21
        ERR_LAMI_MECHANICAL = 22
        ERR_LAMI_TEMPERATURE = 23
        ERR_LAMINATE = 24
        ERR_LAMINATE_END = 25
        CFG_EXTENDED_RESOLUTION = 26
        CFG_FLIP = 27
        CFG_MAGNETIC = 28
        INF_CLEAN_2ND_PASS = 29
        INF_CLEAN_LAST_OUTWARRANTY = 30
        INF_CLEANING = 31
        INF_CLEANING_ADVANCED = 32
        INF_CLEANING_REQUIRED = 33
        INF_CLEANING_RUNNING = 34
        INF_CLEAR_LOW = 35
        INF_CLEAR_UNKNOWN = 36
        INF_ENCODING_RUNNING = 37
        INF_FEEDER_NEAR_EMPTY = 38
        INF_PRINTING_RUNNING = 39
        INF_RETRANSFER_RUNNING = 40
        INF_HEATING = 41
        INF_RIBBON_LOW = 42
        INF_SLEEP_MODE = 43
        INF_SLEEP_MODE_FULL = 44
        INF_UNKNOWN_RIBBON1 = 45
        INF_UNKNOWN_RIBBON2 = 46
        INF_UPDATING_FIRMWARE = 47
        INF_WRONG_ZONE_ALERT = 48
        INF_WRONG_ZONE_CLEAR = 49
        INF_WRONG_ZONE_CLEAR_ALERT = 50
        INF_WRONG_ZONE_CLEAR_EXPIRED = 51
        INF_WRONG_ZONE_RIBBON = 52
        INF_WRONG_ZONE_EXPIRED = 53
        DEF_CARD_ON_EJECT = 54
        DEF_CLEAR_ENDED = 55
        DEF_CLEAR_UNSUPPORTED = 56
        DEF_COOLING = 57
        DEF_COVER_OPEN = 58
        DEF_FEEDER_EMPTY = 59
        DEF_HOPPER_FULL = 60
        DEF_NO_CLEAR = 61
        DEF_NO_RIBBON = 62
        DEF_POWER_SUPPLY = 63
        DEF_PRINTER_LOCKED = 64
        DEF_RECEPTACLE_OPEN = 65
        DEF_REJECT_BOX_COVER_OPEN = 66
        DEF_REJECT_BOX_FULL = 67
        DEF_REMOVE_RIBBON = 68
        DEF_RIBBON_ENDED = 69
        DEF_UNSUPPORTED_RIBBON = 70
        DEF_WAIT_CARD = 71
        ERR_BAD_CLEAR = 72
        ERR_BAD_RIBBON = 73
        ERR_BLANK_TRACK = 74
        ERR_CARD_ON_EJECT = 75
        ERR_CLEAR_ENDED = 76
        ERR_CLEAR_ERROR = 77
        ERR_COVER_OPEN = 78
        ERR_FEATURE = 79
        ERR_FEEDER_EMPTY = 80
        ERR_FEEDER_ERROR = 81
        ERR_HEAD_TEMP = 82
        ERR_HOPPER_FULL = 83
        ERR_MAGNETIC_DATA = 84
        ERR_MECHANICAL = 85
        ERR_NO_CARD_INSERTED = 86
        ERR_NO_OPTION = 87
        ERR_READ_MAGNETIC = 88
        ERR_REJECT_BOX_FULL = 89
        ERR_REJECT_BOX_COVER_OPEN = 90
        ERR_RET_TEMPERATURE = 91
        ERR_RIBBON_ENDED = 92
        ERR_RIBBON_ERROR = 93
        ERR_WRITE_MAGNETIC = 94
        AVANSIA_DEF_FEEDER_EMPTY = 95
        AVANSIA_ERR_FEEDER_EMPTY = 96
        AVANSIA_DEF_COVER_OPEN = 97
        AVANSIA_ERR_COVER_OPEN = 98
        AVANSIA_DEF_TEMP_TOOLOW = 99
        AVANSIA_DEF_RIBBON_ENDED = 100
        AVANSIA_ERR_RIBBON_ENDED = 101
        AVANSIA_DEF_RIBBON_ERROR = 102
        AVANSIA_ERR_RIBBON_ERROR = 103
        AVANSIA_DEF_FILM_ENDED = 104
        AVANSIA_ERR_FILM_ENDED = 105
        AVANSIA_DEF_FILM_ERROR = 106
        AVANSIA_ERR_FILM_ERROR = 107
        AVANSIA_DEF_RIBBON_FILM_ENDED = 108
        AVANSIA_ERR_RIBBON_FILM_ENDED = 109
        AVANSIA_ERR_CARD_JAM = 110
        AVANSIA_ERR_SERVICE_CALL = 111
        AVANSIA_ERR_READ_MAGNETIC = 112
        AVANSIA_ERR_WRITE_MAGNETIC = 113
        AVANSIA_ERR_IC_ERROR = 114
        AVANSIA_INF_UNKNOWN_RIBBON = 115
        AVANSIA_ERR_MANUAL_REQUIRED = 116
        AVANSIA_OPT_MAGNETIC = 117
        AVANSIA_OPT_MAGNETIC_JIS2 = 118
        DEF_FEEDER_OPEN = 119
        ERR_FEEDER_OPEN = 120
        INF_LAMI_CLEANING = 121

    @staticmethod
    def from_int(ma: int, mi: int):
        try:
            return State(State.Major(ma), State.Minor(mi))
        except ValueError:
            return State(State.Major.OFF, State.Minor.PRINTER_OFFLINE)

    def __init__(self, ma: Major, mi: Minor):
        self.major = ma
        self.minor = mi
