mod fs;
mod io;

pub use fs::*;
pub use io::*;

/// Two-letter postal code → full state name
pub fn state_abbr_to_name(state: &str) -> Option<&'static str> {
    match state {
        "AL" => Some("Alabama"),
        "AK" => Some("Alaska"),
        "AZ" => Some("Arizona"),
        "AR" => Some("Arkansas"),
        "CA" => Some("California"),
        "CO" => Some("Colorado"),
        "CT" => Some("Connecticut"),
        "DE" => Some("Delaware"),
        "FL" => Some("Florida"),
        "GA" => Some("Georgia"),
        "HI" => Some("Hawaii"),
        "ID" => Some("Idaho"),
        "IL" => Some("Illinois"),
        "IN" => Some("Indiana"),
        "IA" => Some("Iowa"),
        "KS" => Some("Kansas"),
        "KY" => Some("Kentucky"),
        "LA" => Some("Louisiana"),
        "ME" => Some("Maine"),
        "MD" => Some("Maryland"),
        "MA" => Some("Massachusetts"),
        "MI" => Some("Michigan"),
        "MN" => Some("Minnesota"),
        "MS" => Some("Mississippi"),
        "MO" => Some("Missouri"),
        "MT" => Some("Montana"),
        "NE" => Some("Nebraska"),
        "NV" => Some("Nevada"),
        "NH" => Some("New Hampshire"),
        "NJ" => Some("New Jersey"),
        "NM" => Some("New Mexico"),
        "NY" => Some("New York"),
        "NC" => Some("North Carolina"),
        "ND" => Some("North Dakota"),
        "OH" => Some("Ohio"),
        "OK" => Some("Oklahoma"),
        "OR" => Some("Oregon"),
        "PA" => Some("Pennsylvania"),
        "RI" => Some("Rhode Island"),
        "SC" => Some("South Carolina"),
        "SD" => Some("South Dakota"),
        "TN" => Some("Tennessee"),
        "TX" => Some("Texas"),
        "UT" => Some("Utah"),
        "VT" => Some("Vermont"),
        "VA" => Some("Virginia"),
        "WA" => Some("Washington"),
        "WV" => Some("West Virginia"),
        "WI" => Some("Wisconsin"),
        "WY" => Some("Wyoming"),
        "DC" => Some("District of Columbia"),
        "PR" => Some("Puerto Rico"),
        _ => None,
    }
}

/// Two-letter postal code → FIPS code
pub fn state_abbr_to_fips(state: &str) -> Option<&'static str> {
    match state {
        "AL" => Some("01"),
        "AK" => Some("02"),
        "AZ" => Some("04"),
        "AR" => Some("05"),
        "CA" => Some("06"),
        "CO" => Some("08"),
        "CT" => Some("09"),
        "DE" => Some("10"),
        "DC" => Some("11"),
        "FL" => Some("12"),
        "GA" => Some("13"),
        "HI" => Some("15"),
        "ID" => Some("16"),
        "IL" => Some("17"),
        "IN" => Some("18"),
        "IA" => Some("19"),
        "KS" => Some("20"),
        "KY" => Some("21"),
        "LA" => Some("22"),
        "ME" => Some("23"),
        "MD" => Some("24"),
        "MA" => Some("25"),
        "MI" => Some("26"),
        "MN" => Some("27"),
        "MS" => Some("28"),
        "MO" => Some("29"),
        "MT" => Some("30"),
        "NE" => Some("31"),
        "NV" => Some("32"),
        "NH" => Some("33"),
        "NJ" => Some("34"),
        "NM" => Some("35"),
        "NY" => Some("36"),
        "NC" => Some("37"),
        "ND" => Some("38"),
        "OH" => Some("39"),
        "OK" => Some("40"),
        "OR" => Some("41"),
        "PA" => Some("42"),
        "RI" => Some("44"),
        "SC" => Some("45"),
        "SD" => Some("46"),
        "TN" => Some("47"),
        "TX" => Some("48"),
        "UT" => Some("49"),
        "VT" => Some("50"),
        "VA" => Some("51"),
        "WA" => Some("53"),
        "WV" => Some("54"),
        "WI" => Some("55"),
        "WY" => Some("56"),
        "PR" => Some("72"),
        _ => None,
    }
}
