# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ui_release_stream_controller_api import UiReleaseStreamControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUiReleaseStreamControllerApi(unittest.TestCase):
    """UiReleaseStreamControllerApi unit test stubs"""

    def setUp(self):
        self.api = UiReleaseStreamControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add1(self):
        """Test case for add1

        """
        pass

    def test_delete2(self):
        """Test case for delete2

        """
        pass

    def test_get_all1(self):
        """Test case for get_all1

        """
        pass


if __name__ == '__main__':
    unittest.main()
