# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.aws_elastic_block_store_volume_source import AWSElasticBlockStoreVolumeSource  # noqa: E501
from swagger_client.rest import ApiException


class TestAWSElasticBlockStoreVolumeSource(unittest.TestCase):
    """AWSElasticBlockStoreVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAWSElasticBlockStoreVolumeSource(self):
        """Test AWSElasticBlockStoreVolumeSource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.aws_elastic_block_store_volume_source.AWSElasticBlockStoreVolumeSource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
