# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_time_payload_azure_account import OneTimePayloadAzureAccount  # noqa: E501
from swagger_client.rest import ApiException


class TestOneTimePayloadAzureAccount(unittest.TestCase):
    """OneTimePayloadAzureAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneTimePayloadAzureAccount(self):
        """Test OneTimePayloadAzureAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_time_payload_azure_account.OneTimePayloadAzureAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
