# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: deal.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'deal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndeal.proto\x12\rmetatrader.v1\x1a\x0c\x63ommon.proto\"\x8e\x01\n\x0c\x44\x65\x61lsRequest\x12\x30\n\x0btime_filter\x18\x01 \x01(\x0b\x32\x19.metatrader.v1.TimeFilterH\x00\x12\x10\n\x06ticket\x18\x02 \x01(\x04H\x00\x12\x12\n\x08position\x18\x03 \x01(\x04H\x00\x12\x12\n\x05group\x18\x04 \x01(\tH\x01\x88\x01\x01\x42\x08\n\x06\x66ilterB\x08\n\x06_group\"g\n\rDealsResponse\x12\"\n\x05\x64\x65\x61ls\x18\x01 \x03(\x0b\x32\x13.metatrader.v1.Deal\x12(\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.metatrader.v1.ErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"\xaa\x02\n\x04\x44\x65\x61l\x12\x0e\n\x06ticket\x18\x01 \x01(\x04\x12\r\n\x05order\x18\x02 \x01(\x04\x12\x0c\n\x04time\x18\x03 \x01(\x03\x12\x10\n\x08time_msc\x18\x04 \x01(\x03\x12\x0c\n\x04type\x18\x05 \x01(\x05\x12\r\n\x05\x65ntry\x18\x06 \x01(\x05\x12\r\n\x05magic\x18\x07 \x01(\r\x12\x13\n\x0bposition_id\x18\x08 \x01(\x04\x12\x0e\n\x06reason\x18\t \x01(\x05\x12\x0e\n\x06volume\x18\n \x01(\x01\x12\r\n\x05price\x18\x0b \x01(\x01\x12\x12\n\ncommission\x18\x0c \x01(\x01\x12\x0c\n\x04swap\x18\r \x01(\x01\x12\x0e\n\x06profit\x18\x0e \x01(\x01\x12\x0b\n\x03\x66\x65\x65\x18\x0f \x01(\x01\x12\x0e\n\x06symbol\x18\x10 \x01(\t\x12\x0f\n\x07\x63omment\x18\x11 \x01(\t\x12\x13\n\x0b\x65xternal_id\x18\x12 \x01(\t2\\\n\x13TradeHistoryService\x12\x45\n\x08GetDeals\x12\x1b.metatrader.v1.DealsRequest\x1a\x1c.metatrader.v1.DealsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'deal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEALSREQUEST']._serialized_start=44
  _globals['_DEALSREQUEST']._serialized_end=186
  _globals['_DEALSRESPONSE']._serialized_start=188
  _globals['_DEALSRESPONSE']._serialized_end=291
  _globals['_DEAL']._serialized_start=294
  _globals['_DEAL']._serialized_end=592
  _globals['_TRADEHISTORYSERVICE']._serialized_start=594
  _globals['_TRADEHISTORYSERVICE']._serialized_end=686
# @@protoc_insertion_point(module_scope)
