# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import order_check_pb2 as order__check__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in order_check_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrderCheckServiceStub(object):
    """Service definition for Order Checking
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckOrder = channel.unary_unary(
                '/metatrader.v1.OrderCheckService/CheckOrder',
                request_serializer=order__check__pb2.OrderCheckRequest.SerializeToString,
                response_deserializer=order__check__pb2.OrderCheckResponse.FromString,
                _registered_method=True)


class OrderCheckServiceServicer(object):
    """Service definition for Order Checking
    """

    def CheckOrder(self, request, context):
        """Check if an order can be executed
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderCheckServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOrder,
                    request_deserializer=order__check__pb2.OrderCheckRequest.FromString,
                    response_serializer=order__check__pb2.OrderCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metatrader.v1.OrderCheckService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('metatrader.v1.OrderCheckService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderCheckService(object):
    """Service definition for Order Checking
    """

    @staticmethod
    def CheckOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/metatrader.v1.OrderCheckService/CheckOrder',
            order__check__pb2.OrderCheckRequest.SerializeToString,
            order__check__pb2.OrderCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
