from datasurface.handler.cicd import RepositorywithCICD as RepositorywithCICD
from datasurface.md import ValidationTree as ValidationTree
from datasurface.md.repo import GitHubRepository as GitHubRepository, Repository as Repository

class GitHubCICD(RepositorywithCICD):
    def __init__(self, name: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def createRepositoryForPullRequestRepo(self) -> Repository: ...
