import typing as t
from _typeshed import Incomplete
from hexcore.domain.base import BaseEntity as BaseEntity
from hexcore.domain.events import DomainEvent as DomainEvent
from hexcore.domain.uow import IUnitOfWork as IUnitOfWork
from sqlalchemy.ext.asyncio import AsyncSession as AsyncSession

class SqlAlchemyUnitOfWork(IUnitOfWork):
    session: Incomplete
    def __init__(self, session: AsyncSession) -> None: ...
    async def __aexit__(self, exc_type: type | None, exc_val: BaseException | None, exc_tb: t.Any | None) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    def collect_entity(self, entity: BaseEntity) -> None: ...

class NoSqlUnitOfWork(IUnitOfWork):
    def __init__(self) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type: type | None, exc_val: BaseException | None, exc_tb: t.Any | None) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    def collect_entity(self, entity: BaseEntity): ...
