class Contains:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class CoveredBy:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Covers:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Crosses:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Disjoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Equals:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Intersects:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Overlaps:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Touches:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Within:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
