from collections.abc import Iterable

def concat(*args: object, sep: str = ' ') -> str: ...
def remove_prefix(prefix: str, s: str) -> str: ...
def cslq(iterable: Iterable[str]) -> str: ...
def csl(iterable: Iterable[str]) -> str: ...
def sub(pattern: str, num: int, arg: str): ...
