# -*- coding: utf-8 -*-

"""
pandascorerestapiforallvideogames

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DeletionIncidentChangeTypeEnum(object):

    """Implementation of the 'DeletionIncidentChangeType' enum.

    Attributes:
        DELETION: The enum member of type str.

    """
    DELETION = 'deletion'

