class CoordDim:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class EndPoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class NDims:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class NPoints:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class NumInteriorRings:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class StartPoint:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class X:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Y:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class Z:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class M:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class GeometryType:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...

class STGeometryType:
    def __init__(self) -> None: ...
    def __datafusion_scalar_udf__(self) -> object: ...
