from _typeshed import Incomplete
from enum import Enum

class PermissionsEnum(str, Enum):
    SUPERUSER = '__all__'
    ROLES_VIEW = ...
    ROLES_CREATE = ...
    ROLES_EDIT = ...
    ROLES_DELETE = ...
    USERS_CREATE = ...
    USERS_VIEW = ...
    USERS_INVITE = ...
    USERS_EDIT = ...
    USERS_DELETE = ...
    USERS_ADD_ROLE = ...
    TENANTS_VIEW = ...
    TENANTS_EDIT = ...
    LOGISTICS_INVENTORY_VIEW = ...
    LOGISTICS_INVENTORY_ADJUST = ...
    LOGISTICS_PRODUCTS_MANAGE = ...

OWNER_EXCLUDED_PERMISSIONS: Incomplete

def get_all_permission_values() -> set[str]: ...
def get_owner_permissions() -> set[str]: ...
