# pico_ioc/plugins.py
from typing import Protocol, Any
from .container import Binder, PicoContainer

class PicoPlugin(Protocol):
    def before_scan(self, package: Any, binder: Binder) -> None: ...
    def visit_class(self, module: Any, cls: type, binder: Binder) -> None: ...
    def after_scan(self, package: Any, binder: Binder) -> None: ...
    def after_bind(self, container: PicoContainer, binder: Binder) -> None: ...
    def before_eager(self, container: PicoContainer, binder: Binder) -> None: ...
    def after_ready(self, container: PicoContainer, binder: Binder) -> None: ...

