
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-09-13T14:21:43+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "659852a3d48c5da5d58b2c845df0b6577d368c6e",
 "version": "1.71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
