# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.release_stream_request import ReleaseStreamRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestReleaseStreamRequest(unittest.TestCase):
    """ReleaseStreamRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseStreamRequest(self):
        """Test ReleaseStreamRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.release_stream_request.ReleaseStreamRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
