# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.ui_project_type_controller_api import UiProjectTypeControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUiProjectTypeControllerApi(unittest.TestCase):
    """UiProjectTypeControllerApi unit test stubs"""

    def setUp(self):
        self.api = UiProjectTypeControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_project_type(self):
        """Test case for add_project_type

        Add a new project type  # noqa: E501
        """
        pass

    def test_delete_project_type(self):
        """Test case for delete_project_type

        Delete a project type  # noqa: E501
        """
        pass

    def test_get_all_project_types(self):
        """Test case for get_all_project_types

        Get all project types  # noqa: E501
        """
        pass

    def test_get_project_type_by_id(self):
        """Test case for get_project_type_by_id

        Get project type by ID  # noqa: E501
        """
        pass

    def test_update_project_type(self):
        """Test case for update_project_type

        Update an existing project type  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
