# coding: utf-8

"""
    Control-plane

    API Documentation  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.push_credentials_response import PushCredentialsResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestPushCredentialsResponse(unittest.TestCase):
    """PushCredentialsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPushCredentialsResponse(self):
        """Test PushCredentialsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.push_credentials_response.PushCredentialsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
